language: ruby

sudo: required
dist: trusty
addons:
  chrome: stable

before_install:
  - gem install selenium-webdriver
  - wget -N https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - sudo mv -f ~/Downloads/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

install:
  - bundle install

script: bundle exec rspec
